### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by PabloGirol** [Javinator9889/Discord-PPA#1]
The repository gives me a 403 while apt updating or downloading manually packages.gz, this happens for the stable version and the beta ones

**Comment by Javinator9889** [comment]
Hi,

This is very probably because of the key: the server was migrated so the key changed.

Please, try removing the old key
`sudo apt-key del 5890E288F7ED6702`

and adding the new one:
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 08633B4AAAEB49FC`

Then, do an `sudo apt-get update` and `sudo apt-get install discord`.

Please, keep me updated with any changes and/or errors you may have

**Comment by Javinator9889** [comment]
Ok, there was an error with some permissions, so it gave a 403 error

**Comment by PabloGirol** [comment]
Fixed, thank you
