### ISSUE TITLE
Debian 11 Bullseye

### ISSUE THREAD

**Issue by felsgaertner** [Javinator9889/Discord-PPA#5]
Hi,

Debian 11 has problems resolving dependencies to libappindicator1.  
There is a workaround on [Reddit: How to install Discord on Debian Bullseye
](https://www.reddit.com/r/debian/comments/nci3vl/how_to_install_discord_on_debian_bullseye/)

I would be nice if you could automate this change to enable the installation on Bullseye...

**Comment by Javinator9889** [comment]
Hello,

First, thanks for the issue ☺️  
I've been having a look at [Debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037) and it seems that this is not an issue but an intended feature, so currently the problem is on Discord's side

I may try to implement this and include a hole new distribution that may define an specific Discord `deb` package for Debian 11 bullseye and derivatives, but will take some time

I'll update this issue with further information if I finally decide to implement a new distribution :)

**Comment by Javinator9889** [comment]
It's been a long time since this issue was opened. However, Discord finally decided to build the package for the Bullseye distro properly. Therefore, this issue doesn't make sense anymore **as the package can be installed without any further configuration**, as it used to be.
